framework:
    http_client:
        scoped_clients:
            binance.client:
                base_uri: 'https://api.binance.com'
                timeout: 5
            kraken.client:
                base_uri: 'https://api.kraken.com'
                timeout: 5
            coinbase.client:
                base_uri: 'https://api.coinbase.com'
                timeout: 5
            coingecko.client:
                base_uri: 'https://api.coingecko.com'
                timeout: 10
